AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dockcheck AWS Lambda hello example

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      Runtime: python3.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get
